
#####################################################
################     spring核心配置     #############
#####################################################
#添加运行参数  --spring.config.location=classpath:/config/pro/ --spring.profiles.active=pro


#系统配置
server:
  port: 80
#debug: true


spring:
  main:
    #懒加载配置
    #  全局懒加载 基本上会加入spring容器的bean都会懒加载  filter除外
    #  也可以通过main方法调用SpringApplicationBuilder#lazyInitialization  或者SpringApplication#setLazyInitialization
    lazy-initialization: false
  profiles:
    include:
      - mysql
      - redis
      - value
#    active: mysql,redis,value

#  健康检查配置 Actuator
management:
  endpoint:
    health:
      enabled: true
      show-details: always
